name: TestCafe Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install TestCafe
      run: npm install -g testcafe

    - name: Install project dependencies
      run: npm install

    - name: Run TestCafe tests login
      run: testcafe chromium:headless ./test/login.js

    - name: Run TestCafe tests reset
      run: testcafe chromium:headless ./test/reset.js

    - name: Run TestCafe tests Acerca de
      run: testcafe chromium:headless ./test/acercaDe.js

    - name: Run TestCafe tests cuarto
      run: testcafe chromium:headless ./test/cuarto.js

    - name: Run TestCafe tests inicio
      run: testcafe chromium:headless ./test/inicio.js

    - name: Run TestCafe tests mis cuartos
      run: testcafe chromium:headless ./test/misCuartos.js

    - name: Run TestCafe tests zonas
      run: testcafe chromium:headless ./test/zonas.js



